#ifndef BLOCKLYFLUIDICMACHINETRANSLATOR_GLOBAL_H
#define BLOCKLYFLUIDICMACHINETRANSLATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BLOCKLYFLUIDICMACHINETRANSLATOR_LIBRARY)
#  define BLOCKLYFLUIDICMACHINETRANSLATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BLOCKLYFLUIDICMACHINETRANSLATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BLOCKLYFLUIDICMACHINETRANSLATOR_GLOBAL_H
